services:
  web:
    build: ./
    ports:
      - "8001:8001"
    restart: always
  POSTGRES_LOG:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: POSTGRES_LOG
    ports:
      - "5433:5432"
    restart: always
  adminer:
    image: adminer
    ports:
      - "8081:8081"
    restart: always