version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    command: python3 controller.py
    volumes:
      - .:/usr/src/app
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  postgres_data:
