version: '3.8'

services:
  user_service:
    build: ./user_service
    ports:
      - "8000:8000"
    restart: always

  notification_service:
    build: ./notification_service
    ports:
      - "8002:8002"
    restart: always

  log_service:
    build: ./log_service
    ports:
      - "8001:8001"
    restart: always

  POSTGRES:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: POSTGRES
    ports:
      - "5432:5432"
    restart: always

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log_forwarder.sh:/usr/local/bin/log_forwarder.sh:ro
      - ./nginx/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    depends_on:
      - user_service
      - notification_service
      - log_service
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
