services:
  web:
    build: ./
    ports:
      - "8002:8002"
    restart: always
  POSTGRES_IMAGE:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: POSTGRES_IMAGE
    ports:
      - "5434:5432"
    restart: always
  adminer:
    image: adminer
    ports:
      - "8082:8082"
    restart: always