services:
  web:
    build: ./
    ports:
      - "8000:8000"
    restart: always
  POSTGRES_IMAGE:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: POSTGRES_IMAGE
    ports:
      - "5432:5432"
    restart: always
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always